package schema

import (
	"fmt"
	"strings"
)

// RenderMigration renders a diff as the body of a migration .sql file: a header
// comment noting how it was generated and any warnings, followed by each change
// grouped under a comment. It returns the file contents.
func RenderMigration(d *Diff) string {
	var b strings.Builder
	b.WriteString("-- Generated by `kethosbase db diff`.\n")
	b.WriteString("-- Review before applying: ALTER TYPE / SET NOT NULL can rewrite or reject data,\n")
	b.WriteString("-- and this diff does not cover indexes, keys, constraints, or default expressions.\n")

	if len(d.Warnings) > 0 {
		b.WriteString("--\n-- Warnings (not applied):\n")
		for _, w := range d.Warnings {
			b.WriteString("--   * ")
			b.WriteString(w)
			b.WriteByte('\n')
		}
	}
	b.WriteByte('\n')

	if d.Empty() {
		b.WriteString("-- No changes: the declared schema matches the database.\n")
		return b.String()
	}

	for _, c := range d.Changes {
		marker := ""
		if c.Destructive {
			marker = " [destructive]"
		}
		fmt.Fprintf(&b, "-- %s: %s%s\n", c.Kind, c.Object, marker)
		b.WriteString(c.SQL)
		if !strings.HasSuffix(strings.TrimSpace(c.SQL), ";") {
			b.WriteByte(';')
		}
		b.WriteString("\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}
